repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
-   repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
    -   id: black
-   repo: https://github.com/pre-commit/mirrors-pylint
    rev: v2.7.4
    hooks:
    -   id: pylint
        args: [--disable=E0401]
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.961
    hooks:
    -   id: mypy
        args: [--ignore-missing-imports]
        additional_dependencies: [types-botocore==1.0.2, types-cryptography==3.3.21, types-freezegun==1.1.9, types-httplib2==0.20.4, types-mock==4.0.13, types-paramiko==2.10.0, types-psycopg2==2.9.13, types-python-dateutil==2.8.15, types-requests==2.27.26, types-six==1.16.15, types-urllib3==1.26.14 ]

-   repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
    -   id: isort
        name: isort (python)
        args: ["--profile", "black"]
