coverage:
  status:
    project:
      default:
        # basic
        target: auto
        threshold: 0%
       # advanced settings
        if_ci_failed: error #success, failure, error, ignore
        only_pulls: false
        if_not_found: failure
