#!/bin/bash -ex
TEMPDIR="$(mktemp -d)"
python -m venv "$TEMPDIR"
"$TEMPDIR"/bin/pip install .
"$TEMPDIR"/bin/pip install ".[dev]"
"$TEMPDIR"/bin/pip freeze | grep -v "pkg-resources" | sort > constraints.txt
rm -rf "$TEMPDIR"
